### ISSUE TITLE
Not annotation / check when pull request builds, work only for pushed branches

### ISSUE THREAD

**Issue by Milerius** [report-ci/scripts#11]
Can we change this ?

https://github.com/KomodoPlatform/antara-gaming-sdk/pull/2/checks

I have no checks that appear but:

I have runs here: https://github.com/KomodoPlatform/antara-gaming-sdk/runs/217873300

Can we solve this ?

**Comment by klemens-morgenstern** [comment]
I don't get it, you have the annotations on 56e3e9fe44, but non appear with 35165700 ? What exactly should be changed?

**Comment by Milerius** [comment]
@klemens-morgenstern No i mean i have annotation when i do travis pushed on every push

but when i use travis only with pull request mode i dont have annotation
