### ISSUE TITLE
report-ci doesn't work with github actions

### ISSUE THREAD

**Issue by Milerius** [report-ci/scripts#14]
https://github.com/KomodoPlatform/antara-gaming-sdk/pull/48/checks?check_run_id=233924028

Publishing failed: HTTP Error 401: Unauthorized
{"error":"Missing api token"}

let me know if we can implement support together for it (auto detecting github actions)

**Comment by Milerius** [comment]
and we get a 422 unprocessable entity when using `REPORT_CI_TOKEN` manually

everything work as expected on TRAVIS, but we want to switch to github actions if it's possible

**Comment by Milerius** [comment]
```bash
cd build/bin/unit_tests
  curl https://report.ci/upload.py --output upload.py && python upload.py --include='*.xml' -n "Doctest [github-actions ubuntu-latest-clang8-debug]" --merge ".*"
  shell: /bin/bash -e {0}
  env:
    REPORT_CI_TOKEN: ***
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 31002  100 31002    0     0   183k      0 --:--:-- --:--:-- --:--:--  183k
    No CI detected.
    Commit hash: 053b517aa5737dc90b03d25bb1ba37585729719f

    Root dir: /home/runner/work/antara-gaming-sdk/antara-gaming-sdk
    Project: KomodoPlatform/antara-gaming-sdk
    Found /home/runner/work/antara-gaming-sdk/antara-gaming-sdk/build/bin/unit_tests/antara_lua_tests-result.xml, looks like doctest
    Found /home/runner/work/antara-gaming-sdk/antara-gaming-sdk/build/bin/unit_tests/antara_core_tests-result.xml, looks like doctest
    Found /home/runner/work/antara-gaming-sdk/antara-gaming-sdk/build/bin/unit_tests/antara_event_tests-result.xml, looks like doctest
    Found /home/runner/work/antara-gaming-sdk/antara-gaming-sdk/build/bin/unit_tests/antara_timer_tests-result.xml, looks like doctest
    Found /home/runner/work/antara-gaming-sdk/antara-gaming-sdk/build/bin/unit_tests/antara_scenes_tests-result.xml, looks like doctest
    Found /home/runner/work/antara-gaming-sdk/antara-gaming-sdk/build/bin/unit_tests/antara_config_tests-result.xml, looks like doctest
    Found /home/runner/work/antara-gaming-sdk/antara-gaming-sdk/build/bin/unit_tests/antara_world_tests-result.xml, looks like doctest
    Found /home/runner/work/antara-gaming-sdk/antara-gaming-sdk/build/bin/unit_tests/antara_ecs_tests-result.xml, looks like doctest
Doctest detected
Publishing failed: HTTP Error 422: Unprocessable Entity
{"error":"Some error occured while uploading the report"}
##[error]Process completed with exit code 1.
```

**Comment by Milerius** [comment]
And i think we can use those env variable: https://help.github.com/en/articles/virtual-environments-for-github-actions#default-environment-variables

**Comment by Milerius** [comment]
and the raws logs for the xml output, (seem's processable for me): https://pipelines.actions.githubusercontent.com/Cu79r6Jt5741FcIlLztndo418yVqEHEGgmC07r5UEbNzJri5ur/5df637e5-99a0-4a6e-a9bc-d94c178d0af2/_apis/pipelines/1/runs/25/signedlogcontent/10?urlExpires=2019-09-24T10%3A58%3A50.5177152Z&urlSigningMethod=HMACV1&urlSignature=sDauS9DEJQLo6hWdpIwlDKTlToK0R0WcDjjfRUeY%2BBU%3D

**Comment by Milerius** [comment]
logs archive: 
[logs_26.zip](https://github.com/report-ci/scripts/files/3647353/logs_26.zip)

**Comment by s0undt3ch** [comment]
This looks like a pretty simple addition to the upload script?
No traction since September last year?

**Comment by s0undt3ch** [comment]
* `root_dir`: `GITHUB_WORKSPACE`
* `build_id`: `GITHUB_RUN_ID:GITHUB_RUN_NUMBER`?
* `sha`: `GITHUB_SHA
GITHUB_REPOSITORY`
* `branch`: `GITHUB_REF` or `GITHUB_HEAD_REF`
* `slug`: `GITHUB_REPOSITORY`
* `pr`: ?

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables#default-environment-variables

**Comment by s0undt3ch** [comment]
What variables are actually required?

**Comment by klemens-morgenstern** [comment]
The variables are not the issue, in order for the token less reporting to work we need to add github actions to the backend too, as a double check that the build is actually valid. I am currently reworking that, so I'll see if I can add that.

**Comment by s0undt3ch** [comment]
I'm able to set the token as a secret on my repo and set it as an env variable on the workflow.
So that part is not currently a blocker, although I did get the 422 when uploading my pytest xml junit report.

**Comment by klemens-morgenstern** [comment]
Ah ok, found it, has nothing to do with Github actions, but with github being pedantic. Your timestamp is `2020-02-09T10:09:24.965460` and github expect `YYYY-MM-DDTHH:MM:SSZ`.

I'll need to add a sanitizer there, I hope I'll have it done by next weekend.

**Comment by s0undt3ch** [comment]
Timestamp from?
The report?

Just wanted to see if I can do anything on my end.

**Comment by klemens-morgenstern** [comment]
Well in theory, you could modify the JUnit file and reformat the time string. I really think report.ci should take care of that though.

What version of JUnit are you using?

**Comment by s0undt3ch** [comment]
```
'{"error":"Some error occured while uploading the report"}'
{"links":[{"href":"/api/v1/submissions/61258","rel":"self","type":"GET"}],"requestId":"f556228a-47fb-4666-b617-f93c2751fc3e","status":"active"}
```
If this helps you debug.

**Comment by s0undt3ch** [comment]
This is a recent pytest version, and they changed to xunit2
```
/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/_pytest/junitxml.py:436
  /opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/_pytest/junitxml.py:436: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY
```

**Comment by s0undt3ch** [comment]
Sorry, still in xunit1 apparently.

**Comment by klemens-morgenstern** [comment]
Ok, this is clearly a bug on my side, my pytest test data did not contain timestamps, so it was replaced by `now`. 
If you can disable the timestamp temporarily then you should have a quick workaround. I am unfamiliar with `nox` though, so I don't know how to fix that.

**Comment by s0undt3ch** [comment]
Nox, its tox on steroids and unrelated to pytest :)

I'll check on my end what the report contains and see where that timestamp is coming from.
Thank You!

I'll get back to you.

**Comment by klemens-morgenstern** [comment]
Bugfix turned out easier than expected, just published. Please try again and let's hope I didn't break something new.

**Comment by s0undt3ch** [comment]
https://github.com/s0undt3ch/pytest-salt-factories/runs/434884002?check_suite_focus=true

Didn't change anything on my end, just restarted the build. Same 422.

Thank You for looking into it though!

**Comment by s0undt3ch** [comment]
On [this](https://github.com/s0undt3ch/pytest-salt-factories/runs/434930749?check_suite_focus=true) run I `cat` the XML report and I also changed to `xunit2` which will be the default for pytest 6.x

**Comment by klemens-morgenstern** [comment]
Does it work if you replace `curl https://report.ci/upload.py` with `https://raw.githubusercontent.com/report-ci/scripts/master/upload.py` ?

It seems the timestamp issue is fixed, now the upload script seems outdated.

**Comment by s0undt3ch** [comment]
Yep! Seems to have worked!

**Comment by s0undt3ch** [comment]
Thank You!

**Comment by klemens-morgenstern** [comment]
The new script is now available at `https://report.ci/report.py` and includes token less access for github actions. I have not thoroughly tested it (yet) though.
