### ISSUE TITLE
Can't get report CI to work

### ISSUE THREAD

**Issue by sgammon** [report-ci/scripts#15]
I'm trying to use ReportCI via Github Marketplace. First things first, it's really tough to use the web interface - it kept breaking when trying to request an API token for personal account use. I finally figured out that I can attach it to an organization and it roughly works to get me a token.

But then, I pass a token in via an environment variable (`REPORT_CI_TOKEN`, as I saw in another issue), but it still gives me a 403? With the following error:

```
Reporting test results...
    No CI detected.
    Commit hash: 1f33dc867fae910a28a5ce05836bd586100844a2
    Root dir: /Volumes/PITBULL/Vault/GUST
    Project: sgammon/GUST
    Found /Volumes/PITBULL/Vault/GUST/reports/tests.xml, looks like some xUnit
junit selected
Publishing failed: HTTP Error 403: Forbidden
{"error":"Some error occured while uploading the report"}
```

Granted, the user (`sgammon`) is different than the org for which the token is issued, so perhaps that's the problem. How can I get this to work for a personal repo that's public?

**Comment by klemens-morgenstern** [comment]
Thanks for the feedback, I am really sorry you ran into trouble. 

You need to have a personal installation (which I found in the database) so you should be able to get a personal token.

However, the GUST repository is private and we only offer this service for open-source projects at the moment. I hope the version for private repositories will be online soon (very few weeks I hope).

**Comment by sgammon** [comment]
@klemens-morgenstern i had published the project (publicly) for a while to test with Report CI, but it didn't work :( the personal token can't be acquired from the dashboard. for me, when my personal account is selected, it just displays an empty input.

**Comment by sgammon** [comment]
@klemens-morgenstern here are screenshots of what i see

<img width="671" alt="Screen Shot 2020-02-24 at 2 24 20 PM" src="https://user-images.githubusercontent.com/171897/75196745-76f43d80-5711-11ea-932c-575ffc8553cf.png">

and after clicking "Show Token":
<img width="737" alt="Screen Shot 2020-02-24 at 2 24 34 PM" src="https://user-images.githubusercontent.com/171897/75196765-7d82b500-5711-11ea-868c-e21f0d62228a.png">

and after clicking "Generate new token":
<img width="760" alt="Screen Shot 2020-02-24 at 2 25 41 PM" src="https://user-images.githubusercontent.com/171897/75196811-93907580-5711-11ea-9f58-b6eb6ddc0b71.png">

**Comment by klemens-morgenstern** [comment]
For some reason there seems to be a bug in my backend, where you didn't get authorized for the installation. I just added you manually, so you should be able to fetch the token now.

**Comment by vektory79** [comment]
Same here. I can't get the token too.
Any progress to solve this issue?

Thanks.

**Comment by klemens-morgenstern** [comment]
Should be fixed now, please check. Sorry about that, had a false assumption about the order of login & installation.

**Comment by sgammon** [comment]
@klemens-morgenstern no worries in fact this works for me and has for a few days

I’ll leave open for the other commenters but feel free to close if we’re only tracking the one issue

**Comment by vektory79** [comment]
WOW! It's worked now!

Thanks very much, @klemens-morgenstern, for a such great tool!

**Comment by gupascal** [comment]
Hello,

Same issue here: On the Settings page, I can not generate a token.
@klemens-morgenstern  Could you help me please ?

Also, the Settings page displays nothing for me on Firefox... But works with Chrome...

Thank you.

**Comment by klemens-morgenstern** [comment]
Hey @gupascal,

I had a major transition going on which caused a few issues in the database (and kept me busy the last days), which I am really sorry about. I just deployed the full update, because that broke the installation for you. 

I hope it works now, if not you might need to uninstall/ reinstall. 

I'll be checking out the firefox issue after that is done.

**Comment by klemens-morgenstern** [comment]
I completed the update by now, and hope everything still works after I switched out the entire database system. You can now view reports at https://report.ci/reports/gh/ and actually combine several test frameworks into a single report.

And private repos are now possible.

Will close the issue, please feel free to open it again / another one if you run into problems or have features ideas!
