### ISSUE TITLE
No test data to upload

### ISSUE THREAD

**Issue by moul** [report-ci/scripts#17]
Hi,

I'm trying to use report.ci on a repo, and I got the following message: 
```
  cd reports
  ls -la
  curl -s https://report.ci/upload.py | python - --include='*.json' --framework=go
  shell: /bin/bash -e {0}
  env:
    OS: ubuntu-latest
    GOLANG: 1.14
    GOROOT: /opt/hostedtoolcache/go/1.14.4/x64
total 264
drwxr-xr-x  2 runner docker   4096 Jun 22 15:38 .
drwxr-xr-x 19 runner docker   4096 Jun 22 15:38 ..
-rw-r--r--  1 runner docker 260629 Jun 22 15:39 go-Linux-slow.json
    Github actions CI detected.
    Commit hash: b1a041547814c2f37653f0cf065782da154ff47c
    Root dir: /home/runner/work/berty/berty
    Project: berty/berty
Found /home/runner/work/berty/berty/reports/go-Linux-slow.json, looks like GoTest
go selected
 No test data to upload.
##[error]Process completed with exit code 1.
```

Here is the link to the check, I hope it will stay since I will probably git force push soon to cleanup my test commits -> https://github.com/berty/berty/pull/2102/checks?check_run_id=795960547

**Comment by moul** [comment]
a more concise PR on a very minimalist go codebase is available here too -> https://github.com/moul/golang-repo-template/pull/49/checks?check_run_id=796531735

It generates this file:

```json
{"Time":"2020-06-22T20:38:25.888836138+02:00","Action":"run","Package":"moul.io/golang-repo-template","Test":"TestRun"}
{"Time":"2020-06-22T20:38:25.889216181+02:00","Action":"output","Package":"moul.io/golang-repo-template","Test":"TestRun","Output":"=== RUN   TestRun\n"}
{"Time":"2020-06-22T20:38:25.889251427+02:00","Action":"output","Package":"moul.io/golang-repo-template","Test":"TestRun","Output":"            _                                                   _                      _        _            _             _\n"}
{"Time":"2020-06-22T20:38:25.889276992+02:00","Action":"output","Package":"moul.io/golang-repo-template","Test":"TestRun","Output":" __ _  ___ | | __ _  _ _   __ _  ___  _ _  ___  _ __  ___  ___ | |_  ___  _ __   _ __ | | __ _ | |_  ___    | |_  ___  ___| |_\n"}
{"Time":"2020-06-22T20:38:25.889295758+02:00","Action":"output","Package":"moul.io/golang-repo-template","Test":"TestRun","Output":"/ _` |/ _ \\| |/ _` || ' \\ / _` ||___|| '_|/ -_)| '_ \\/ _ \\|___||  _|/ -_)| '  \\ | '_ \\| |/ _` ||  _|/ -_) _ |  _|/ -_)(_-\u003c|  _|\n"}
{"Time":"2020-06-22T20:38:25.889315723+02:00","Action":"output","Package":"moul.io/golang-repo-template","Test":"TestRun","Output":"\\__, |\\___/|_|\\__,_||_||_|\\__, |     |_|  \\___|| .__/\\___/      \\__|\\___||_|_|_|| .__/|_|\\__,_| \\__|\\___|(_) \\__|\\___|/__/ \\__|\n"}
{"Time":"2020-06-22T20:38:25.889335559+02:00","Action":"output","Package":"moul.io/golang-repo-template","Test":"TestRun","Output":"|___/                     |___/                |_|                              |_|\n"}
{"Time":"2020-06-22T20:38:25.889354139+02:00","Action":"output","Package":"moul.io/golang-repo-template","Test":"TestRun","Output":"12 CPUs, /tmp/go-build181866255/b001/golang-repo-template.test, fwrz, go1.14.1\n"}
{"Time":"2020-06-22T20:38:25.889371349+02:00","Action":"output","Package":"moul.io/golang-repo-template","Test":"TestRun","Output":"Hello World! []\n"}
{"Time":"2020-06-22T20:38:25.88939623+02:00","Action":"output","Package":"moul.io/golang-repo-template","Test":"TestRun","Output":"--- PASS: TestRun (0.00s)\n"}
{"Time":"2020-06-22T20:38:25.889423111+02:00","Action":"pass","Package":"moul.io/golang-repo-template","Test":"TestRun","Elapsed":0}
{"Time":"2020-06-22T20:38:25.889458021+02:00","Action":"output","Package":"moul.io/golang-repo-template","Output":"PASS\n"}
{"Time":"2020-06-22T20:38:25.889524147+02:00","Action":"output","Package":"moul.io/golang-repo-template","Output":"coverage: 57.1% of statements\n"}
{"Time":"2020-06-22T20:38:25.901712177+02:00","Action":"output","Package":"moul.io/golang-repo-template","Output":"ok  \tmoul.io/golang-repo-template\t0.023s\tcoverage: 57.1% of statements\n"}
{"Time":"2020-06-22T20:38:25.901760453+02:00","Action":"pass","Package":"moul.io/golang-repo-template","Elapsed":0.023}
```

**Comment by moul** [comment]
I've made some changes on my script and now I get a 401 error :)

I think the problem is not with my repo but with my account, I've no installation and here is the result when I try to refresh installations

![Manfreds-iMac - Screen Shot 2020-06-23 at 00 17 52](https://user-images.githubusercontent.com/94029/85340765-fbe83b80-b4e6-11ea-9f75-866293ffd71d.png)

For your information, I've a lot of repositories on my account and you need to support pagination in order to fetch them all

---

Here is the last run -> https://github.com/moul/golang-repo-template/pull/49/checks?check_run_id=797111080

![Manfreds-iMac - Screen Shot 2020-06-23 at 00 24 35](https://user-images.githubusercontent.com/94029/85341200-ec1d2700-b4e7-11ea-9e8b-433617789604.png)

**Comment by klemens-morgenstern** [comment]
Sorry, I missed the notification for this issue. Looking into it now.

**Comment by klemens-morgenstern** [comment]
Thanks for the bug report. Fixed & deploying now. I did however only find the `berty` installation, not the one for `moul`. 

Did you install for both, i.e. have I missed it?

**Comment by moul** [comment]
Ok cool i will give a new try,

For moul, I have a 500 error when I try to link my account (see my last comment above)

**Comment by klemens-morgenstern** [comment]
But You installed through GitHub? The Berty should show up in the settings as well once you hit refresh.

**Comment by moul** [comment]
Yep, it's installed:

![Screenshot - Manfred 2020-06-29 at 20 02 48](https://user-images.githubusercontent.com/94029/86039960-85e25800-ba43-11ea-907f-6316ab077651.png)

The link seems to be detected by report.ci:

![Screenshot - Manfred 2020-06-29 at 20 03 27](https://user-images.githubusercontent.com/94029/86040022-9c88af00-ba43-11ea-9ae9-fc11089c9d4e.png)

When I click on "refresh", I get only berty repos in the JSON response, and nothing appears on the page

![Screenshot - Manfred 2020-06-29 at 20 05 05](https://user-images.githubusercontent.com/94029/86040179-da85d300-ba43-11ea-902d-d4bd18f47168.png)

**Comment by klemens-morgenstern** [comment]
Thanks for sticking with me through this bug.

So there is your personal installation (into the `moul`) account, which isn't in the database. If you wanna fix this you might need to uninstall & isntall again, which you can do through the `add installation` button. I would highly appreciat that, because this installation doesn't show up in the DB & Logs.

In my user-db I see to accounts, `moul` and `moul-sudo` - and only `moul-sudo` is listed as an administrator for `berty`. I think you need to use `moul-sudo` to get the access token, since report.ci requires admin priviliges. Is it possible you signed up for report.ci with the non-sudo account?

On another note: the github actions build *should*&trade; work without a token now. I didn't have time to thoroughly test it.

**Comment by moul** [comment]
> So there is your personal installation (into the moul) account, which isn't in the database. If you wanna fix this you might need to uninstall & isntall again, which you can do through the add installation button. I would highly appreciat that, because this installation doesn't show up in the DB & Logs.

I just clicked on uninstall, then link it again, nothing on the dashboard, then I clicked again on "refresh installations" -> it was longer than usual, but nothing at the end, and no HTTP error code

When checking the API response, I can see only 33 "berty" repos

> In my user-db I see to accounts, moul and moul-sudo - and only moul-sudo is listed as an administrator for berty. I think you need to use moul-sudo to get the access token, since report.ci requires admin priviliges. Is it possible you signed up for report.ci with the non-sudo account?

Yep, `moul-sudo` is admin on berty and `moul` is a standard user/collaborator without admin privileges and yep it has more options for berty :)

![Screenshot - Manfred 2020-06-30 at 00 00 52](https://user-images.githubusercontent.com/94029/86060327-cbfbe380-ba64-11ea-86e4-afe31bba1118.png)

**Comment by moul** [comment]
I just gave a try on a berty repo without setting up the token as secret: https://github.com/berty/berty/runs/820280441?check_suite_focus=true

![Screenshot - Manfred 2020-06-30 at 00 32 10](https://user-images.githubusercontent.com/94029/86062505-25fea800-ba69-11ea-8fba-a2881ce92b53.png)

Associated PR: https://github.com/berty/berty/pull/2130

---

Now I will give a try with a secret

**Comment by klemens-morgenstern** [comment]
You weren't kidding about that being a lot of repositories. The timeouts kick in, it's not even close. I'll add your personal account manually, should be up in a few minutes.

**Comment by moul** [comment]
hehe :)

you're not the first product I "break" :)

fyi -> https://report.ci/reports/gh/berty/berty/tree/0e3bed3ba8af39bc90308b36d158f272efb8f9f5 with manual secrets it works on berty!

**Comment by klemens-morgenstern** [comment]
I found another bug in the github actions checker, should work without now, too. But I guess if you have it working, why change it. 

I added your repositories, could you double check if you can access the installation?

**Comment by moul** [comment]
Yep, it looks good now

![Screenshot - Manfred 2020-06-30 at 00 57 31](https://user-images.githubusercontent.com/94029/86064151-b12d6d00-ba6c-11ea-802e-9bc343115d7d.png)

:+1:

**Comment by moul** [comment]
Closing this issue, thank you for this personal support :)

**Comment by klemens-morgenstern** [comment]
My pleasure, thanks for your patience. Any further issues & bug reports are highly appreciated!
