### ISSUE TITLE
Trying to use report-ci with doctest in my own project result

### ISSUE THREAD

**Issue by Milerius** [report-ci/scripts#3]
The command "./service-test --reporters=xml --out=result.xml -s || true" exited with 0.
1.04s$ curl https://report.ci/upload.py | python
    Travis CI detected.
    Commit hash: 074e91273976ba317fa7ea8055fb45a64e4f9057
    Root dir: /home/travis/build/raven-os/albinos
    Project: raven-os/albinos
    Found /home/travis/build/raven-os/albinos/build/tests/result.xml, looks like doctest
Doctest detected
Publishing failed: HTTP Error 401: Unauthorized
Ill-formed CI request
The command "curl https://report.ci/upload.py | python" exited with 1.
0.00s$ cd ..
The command "cd .." exited with 0.

https://github.com/raven-os/Albinos It's a corporate public project (an operating system)

my travis: https://github.com/raven-os/albinos/blob/roman_dev_15/.travis.yml
travis result: https://travis-ci.org/raven-os/albinos/builds/512916250?utm_source=github_status&utm_medium=notification

Seem's that i miss an authorization, i have to change something ? 

Best Regards,

Roman Sztergbaum

**Comment by klemens-morgenstern** [comment]
It seems I forgot the most important information for the service: you need to sign up. You can sign in at report.ci (in case you need a token) and install the app here: https://github.com/apps/report-ci

**Comment by Milerius** [comment]
Oh thanks a lot o will retry and close the issue if't solve my problems

**Comment by klemens-morgenstern** [comment]
Thanks though, the sign-in button of report.ci was at the button :(, so no wonder you missed it.

**Comment by Milerius** [comment]
@arignir give the right for raven_os/albinos

The error still occurred after giving rights to the repository, do we miss something ? 
curl https://report.ci/upload.py | python
    Travis CI detected.
    Commit hash: 11f8d58c1832c53ce35b376cfff0e10477f325be
    Root dir: /home/travis/build/raven-os/albinos
    Project: raven-os/albinos
    Found /home/travis/build/raven-os/albinos/build/tests/result.xml, looks like doctest
Doctest detected
Publishing failed: HTTP Error 401: Unauthorized
Ill-formed CI request
The command "curl https://report.ci/upload.py | python" exited with 1.

**Comment by Milerius** [comment]
Should we close the pull request and reopen it for example ?

it's from a pull request from my branch : roman_dev_15 into master

**Comment by klemens-morgenstern** [comment]
Oh, you're building on travis-ci.ORG, not .COM. I forgot I didn't add that yet, since new repos are only used at travis-ci.COM. 
Just added code to handle that, can you restart the build on travis?

**Comment by Milerius** [comment]
Ok on going

**Comment by Milerius** [comment]
https://travis-ci.org/raven-os/albinos/builds/512970353?utm_source=github_status&utm_medium=notification

Still occur

**Comment by klemens-morgenstern** [comment]
Ah, that was stupid typo, my bad. Really sorry, I just can't add new repos to travis-ci.org, so it's hard to test. Can you restart in 5 min.?

Sorry to test your patience.

PS: the reason is the tokenless access - I need to check for the job on travis-ci, otherwise everyone could just push test data to any open source project, which isn't really secure.

**Comment by Milerius** [comment]
Ok let me know when I need to retry ! We will get it :)

**Comment by Milerius** [comment]
Doctest detected
Publishing failed: HTTP Error 404: Not Found
Unknown job

Not 401 error anymore but 404

**Comment by klemens-morgenstern** [comment]
Ah, that seems to be the PR build - the push version works: https://github.com/raven-os/albinos/pull/96/checks?check_run_id=88079337

Will check!

**Comment by Milerius** [comment]
Ah yes great !

Let me know when you figure out for the pull request and thanks a lot for your work is gorgeous

**Comment by klemens-morgenstern** [comment]
Alright, was using the hash there, script should be repaired now.

**Comment by Milerius** [comment]
Everything work thanks a lot !
