### ISSUE TITLE
Boilerplate reporting in commentary of a pull request make the review almost impossible for unit test file

### ISSUE THREAD

**Issue by Milerius** [report-ci/scripts#5]
Hello i love report.ci and use it into 11 differents configuration:

<img width="433" alt="Capture d’écran 2019-04-19 à 23 32 31" src="https://user-images.githubusercontent.com/21139416/56445009-7160e680-62fb-11e9-9e54-d75271dc4139.png">

There is anyway to reduce the posting ? i was looking about anotation but doesn't seems related to my need's

repository: https://github.com/Milerius/nephtys

**Comment by klemens-morgenstern** [comment]
There isn't really, since those are seperate check_runs. I will look into it though,maybe I can query that and remove duplicates.

In the meantime, you could turn off the '-s' flag for reporting passed tests. but I guess you would actually want one annotation per passed test, right, right?

**Comment by Milerius** [comment]
I want it reported one time at least yeah !

**Comment by klemens-morgenstern** [comment]
So if you set a flag that will only create the annotation for the first run and ignore allthe other if identical would that be fine?

Because that might look like there's no feedback from the other test runs and it might vary which is the first.

**Comment by Milerius** [comment]
yes it's will be perfect, how can i do that ?

**Comment by klemens-morgenstern** [comment]
Wait for a week until I implement it ;).

I would just compare the text of the Annotation, so if two systems generate different results you'd still get two messages. But it shouldn't spam. 

Would it be okay if you don't get told that a duplicate got removed?

**Comment by Milerius** [comment]
Ok great !

**Comment by klemens-morgenstern** [comment]
Added it, You can now add a "--merge" for the annotate & publish script with a regex. The regex matches the check_run you want to merge with (e.g. you could restrict it to windows builds) or you can just pass a `.*`.

So adding `--merge .*` should do the trick for you. 

Please let me know if it works for you.

**Comment by Milerius** [comment]
i got something like `upload.py: error: unrecognized arguments: ..` for the moment

```bash
curl https://report.ci/upload.py --output upload.py && python upload.py -n "${doctest_upload_name}" --merge .*
```

**Comment by klemens-morgenstern** [comment]
my bad, you need to put the regex in quotes on linux; sorry only tested it on my windows machine.

**Comment by Milerius** [comment]
Ok I will test it later when I come back

**Comment by Milerius** [comment]
Work's like a charm thank's.
