### ISSUE TITLE
Regex not matching output Azure Pipelines

### ISSUE THREAD

**Issue by KROSF** [report-ci/scripts#6]
regex is not matching this output:

```
origin	https://github.com/user/repo (fetch)
origin	https://github.com/user/repo (push)
```

**Comment by KROSF** [comment]
I use this regex to match that output
```py
r"https:\/\/github.com\/([-_A-Za-z0-9]+)\/([-_A-Za-z0-9]+)(.git)*"
```

**Comment by KROSF** [comment]
**suggestion to match more outputs with one regex**

![regex](https://user-images.githubusercontent.com/24454660/58375143-c623fc80-7f4c-11e9-8b90-c4670a574096.png)

**Comment by klemens-morgenstern** [comment]
Weird, I thought github always appends the `.git`. The problem is that your suggestions won't work if you have a `.` in the project name - which is a allowed (e.g. https://github.com/klemens-morgenstern/metal.test).

So I'll use a negative look-ahead:

```regex
https:\/\/github.com\/([-_A-Za-z0-9]+)\/((?:(?!\.git(?:\s|$))[-._A-Za-z0-9])+)
```

Is that only an issue with `https` or also `ssh` links for you?

**Comment by KROSF** [comment]
Also happens with ssh links your current solution only match links that start by git@ in ssh links.
Adding this **(?::|\/)** after github.com and removing any prefix before github.com fix the problem for all github links no matter it is ssh or https.

**Comment by KROSF** [comment]
last commit works but this https://report.ci/upload.py is pointing to a previous version.

**Comment by klemens-morgenstern** [comment]
Just uploaded 30 min. ago, so you were testing it before that.

Should be fixed, thanks for reporting!
