### ISSUE TITLE
Unable to get api token for github organization account

### ISSUE THREAD

**Issue by KROSF** [report-ci/scripts#7]

**Comment by klemens-morgenstern** [comment]
Thanks for reporting, looking into it now.

It seems to be a race condition I missed, where you install the app first and then sign up. Is that correct or did you do those things in a different order?

**Comment by KROSF** [comment]
I did in reverse order.

**Comment by klemens-morgenstern** [comment]
OK, this is weird then, because that is handled ,because this use case is handled and tested.

You should be able to obtain the token now.

**Comment by KROSF** [comment]
### This is the output that setting pages show me.

![report ci_settings](https://user-images.githubusercontent.com/24454660/58379473-006cb880-7fa4-11e9-97e9-50bd6b165d29.png)

**Comment by KROSF** [comment]
I can get the token, thanks.

**Comment by klemens-morgenstern** [comment]
Awesome, thanks for reporting!
