### ISSUE TITLE
pytest: Publishing failed: HTTP Error 422: Unprocessable Entity

### ISSUE THREAD

**Issue by kshpytsya** [report-ci/scripts#9]
```
$ curl -s https://report.ci/upload.py | python - --include='test-log*.xml' --framework=pytest

    Travis CI detected.

    Commit hash: 2e7f869fdf3c6bf606480733098fdf13267ab4c5

    Root dir: /home/travis/build/[secure]/with-cloud-blob

    Project: [secure]/with-cloud-blob

    Found /home/travis/build/[secure]/with-cloud-blob/test-log.xml, looks like PyTest

pytest selected

Publishing failed: HTTP Error 422: Unprocessable Entity

b'{"error":"Some error occured while uploading the report"}'

The command "curl -s https://report.ci/upload.py | python - --include='test-log*.xml' --framework=pytest" exited with 1.
```

**Comment by klemens-morgenstern** [comment]
Thanks for reporting, is it possible for you to share some details on test framework version or share the output of the test run?

**Comment by s0undt3ch** [comment]
FYI, I've been successfully uploading pytest reports, though, I've defaulted to the xunit2 format on pytest (might still work with xunit1 format though)

**Comment by klemens-morgenstern** [comment]
Is the issue still open?

**Comment by kshpytsya** [comment]
I never got back to using `report-ci` after the initial failure due to the lack of time.

**Comment by klemens-morgenstern** [comment]
I do understand that, but maybe all the updates can convince you otherwise. This is what my PyTest example produces: https://report.ci/reports/gh/report-ci/python-example/rep/447

I'll consider it fixed for, but p lease feel free to reopen if it still doesn't work.
